name: expensetracker
description: "SmartBudget - A personal daily expense tracker with modern dashboard."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Date Formatting
  intl: ^0.19.0
  
  # Path Provider for Hive
  path_provider: ^2.1.2
  
  # Firebase & Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  
  # Google Drive API
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.2.0
  
  # PDF Generation & CSV Export
  pdf: ^3.11.1
  printing: ^5.13.2
  csv: ^6.0.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
